### PR TITLE
Add metrics note

### LINKED ISSUE #32: Ignored quotas and client groups metrics
After enabling the Strimzi quotas plugin, any default Kafka quotas plugin configuration is ignored without any warning and you also lose per client group metrics. The metrics part is a bit annoying, as the plugin only shows the aggregated per quota type metrics (FETCH, PRODUCE, REQUEST), rather than per client group metrics (e.g. my-user, my-user-new). This is useful information when the cluster admin doesn't have access to client-side metrics. I think this behavior is driven by the `ClientQuotaCallback.quotaMetricTags` implementation.

For example, if I have a Kafka CR like this:

```sh
spec:
  kafka:
    config:
      client.quota.callback.class: io.strimzi.kafka.quotas.StaticQuotaCallback
      client.quota.callback.static.storage.check-interval: 30
      client.quota.callback.static.storage.hard: 32212254720
      client.quota.callback.static.storage.soft: 26843545600
   listeners:
    - authentication:
        type: scram-sha-512
      name: external
      port: 9094
      tls: true
      type: route
```

And a KafkaUser CR like this:

```sh
spec:
  authentication:
    type: scram-sha-512
  quotas:
    producerByteRate: 500000
```

There is no throttling if I run a producer at full speed (well over 500 KB/s): 

strimzi-quotas

Instead, this is what happens with the same producer after I remove the `client.quota.callback.*` configs and wait for the rolling update to complete:

default-quotas

### PR DESCRIPTION
**Pull request by fvaleri**
This should close #32.

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
If you think this helps, I'm happy to approve and merge it.

But to be honest, I'm not convinced users will understand what it really means. From the issue I assumed that you would add something like ...

```
Kafka let's you use only one quotas plugin. So if you enable this quotas plugin, the quotas built-in Apache Kafka will stop working and will not produce any metrics.
```

What you add sounds like the quotas will work but only some metrics will not be produced? That seems weird.

Should it also add some names of the metrics? That might also help to understand what exactly it is talking about.

**Comment by fvaleri** [comment]
> I'm not convinced users will understand what it really means.

What about this modified version?

**Review by scholzj — APPROVED** [review]
Yeah, I think this is much easier to understand. Thanks. Can you update the other PR for the operator docs in the same way please? Thanks!

**Comment by fvaleri** [comment]
> Can you update the other PR for the operator docs in the same way please?

It's already updated.

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
